spring:
  datasource:
    # O Spring injeta automaticamente os valores do JSON do segredo
    url: jdbc:mysql:aws://${DB_HOST}:3306/estudo_db
    username: admin
    password: Ximbinha
    driver-class-name: software.aws.rds.jdbc.mysql.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Configuração da Região (Necessário para teste local no Fedora)
spring.cloud.aws.region.static: us-east-1